import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "TypeScript Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`antialiased flex flex-col min-h-screen`}>
        <header>
          <Navbar />
        </header>
        <main className="grow max-w-7xl mx-auto container my-3">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
